### ISSUE TITLE
The Bands in town displaying twice and location needs to be strigngified

### ISSUE THREAD

**Issue by tonymelek** [chrisjmckeown/simone_william_tony_chris#23]
Hi Simone,
Could you please have a look and fix?
Would be awesome if you applied some styling to the output.
Thanks,

**Comment by smoneo** [comment]
thought I fixed this issue with the latest push to master?

**Comment by tonymelek** [comment]
Thanks looks good now. When you get a chance, can you look on when an artist is not found 
![notfund](https://user-images.githubusercontent.com/66405901/93552073-e46c0200-f9b2-11ea-8c97-2d2d13e81364.JPG)
Can you pass the artist name from the "displayBandsInTownData(artistName)" into   appendArtistInfo(response,artistName)
so you can get the name instead of "undefined"

**Comment by smoneo** [comment]
Alright, I've made a pull request to look over. Hopefully it's fine this time

**Comment by tonymelek** [comment]
Thanks Simone. Looks good now
